### ISSUE TITLE
Please support respect/validation 2.1+

### ISSUE THREAD

**Issue by franksl** [thephpleague/openapi-psr7-validator#102]
Hi,
Is it possible to support newer versions of respect/validation library?
I'm using ^2.1 version of respect/validation in my code and found a conflict when trying to require openapi-psr7-validator.
I'm aware that respect/validation requires php 7.3 while this requires php 7.2, maybe an upgrade of php version could be useful here too.
Thanks,
Frank

**Comment by scaytrase** [comment]
It depends on how different package behaves on 1.x and 2.x. For some packages and some usages it's possible to support several versions of dependencies, for some it's not.

The perfect option is to have `respect/validation: ^1 || ^2` in order to get maximum users.

Would you like to try upgrade `respect/validation` here in order to check, how much codebase changes it require? I think we may  take one or another way of sovling this based on that information.

**Comment by franksl** [comment]
I created a pull request, respect/validation has some backwards incompatible changes, so either v1 or v2 can be supported. Hope this helps,
Frank
