### ISSUE TITLE
Migrate from travis-ci to github action

### ISSUE THREAD

**Issue by sunkan** [thephpleague/openapi-psr7-validator#104]
## Why 

Because travis-ci.org is closing and travis-ci.com wont provide free build minutes for open source projects in a simple way.

* https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
* https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/
* https://blog.travis-ci.com/oss-announcement

## Alternatives 

1. Just rewrite the `.travis.yml` as a github action
2. Use a github action like [ktomk/run-travis-yml](https://github.com/marketplace/actions/run-travis-yml)

I think the best solution is 1. because we have a very simple `.travis.yml` file

I can put together a pull-request if you want?

**Comment by scaytrase** [comment]
I'd like to see first solution. But as far my experience with GA is not really good. Maybe you can provide me better example.

So what we need:
* Build matrix with 7.2, 7.3, 7.4 + 8.0 (now it's time!) + nightly (8.1 but better it will update automatically like nightly in travis).
* additional build with 7.2 to run PHP-CS
* Nigtly build is allowed to fail (PR should be mark as valid if it fails, but I should see failed build in GA itself in order to have a list of features to fix)

P.S. Bad news, RIP OSS travis. Thanks for bringing these here

**Comment by sunkan** [comment]
Fixed by #105
