### ISSUE TITLE
Wrong dependency version with league/uri since last update

### ISSUE THREAD

**Issue by callapa** [thephpleague/openapi-psr7-validator#143]
The league/openapi-psr7-validator library in version 0.14.0 uses the league/uri library with version ^6.3. The latter, since version 6.5.0, no longer supports PHP 7.2.x.
The league/uri library version should be forced to 6.4.0 in order to be compatible with the PHP version

**Comment by scaytrase** [comment]
I didn't get the problem. We have test matrix for 7.2 to 8.0 with both highest and lowest possible versions. Everything passes green.

https://github.com/thephpleague/openapi-psr7-validator/runs/3734773540

**Comment by scaytrase** [comment]
I think you misunderstood how the composer works. It's not the library should be compatible with php version. It's about php version being compatible with library requirements. If certain version doesn't match it requirement (because of PHP version or other library requirement( - it's skipped from the choice of allowed versions to be installed. But this leaves 6.3.* and 6.4.* in place allowed to be installed.
