### ISSUE TITLE
OneOf validation always fails

### ISSUE THREAD

**Issue by amenophis** [thephpleague/openapi-psr7-validator#170]
Hello,
I'm trying to use this validator to validate in our test suite that our API respond with data formatted according with our OpenAPI schema.

In our case, we had a route that return a different payload based on a query param, represented by a oneOf in the OpenApi Schema

The exception throw by the validator is: `League\OpenAPIValidation\Schema\Exception\TooManyValidSchemas: Keyword validation failed: Data must match exactly one schema, but matched 2`

I made a reproducer in this repo: https://github.com/amenophis/openapi-psr7-validator-issue

Thanks in advance

**Comment by amenophis** [comment]
Hello,
Do you have information about this issue ?

Thanks in advance

**Comment by kevin92dev** [comment]
Hi, I'm also interested in the solution, I'm having the same problem.

**Comment by jimcottrell** [comment]
This seems to be a misunderstanding of JSON schema validation. @amenophis, maybe you've already figured this out at this point, but for anyone else's benefit, in your test repo you have

```
File:
  description: 'File model'
  properties:
    id:
      type: integer
    filename:
      type: string
  type: object
FileWithInfo:
  description: 'FileWithInfo model'
  properties:
  info:
    $ref: '#/components/schemas/Info'
  file:
    $ref: '#/components/schemas/File'
  type: object
```

And elsewhere

```
oneOf:
  - { $ref: '#/components/schemas/File' }
  - { $ref: '#/components/schemas/FileWithInfo' }
```

But your schema definitions aren't narrow enough for your test data to match only one schema. Since there's no `required` definition, *if* the defined properties exist, the values must match your property definitions, but if the properties don't exist, the schema still matches. You haven't specified that any properties *must* exist.

`additionalProperties: false` would also have allowed the validator to rule out a schema, but that can also get you in trouble if you end up using `allOf` since unless all schemas list the same properties, the schemas are then mutually exclusive.
