### ISSUE TITLE
A package to validate HttpFoundation responses against OpenAPI definitions, built upon yours

### ISSUE THREAD

**Issue by osteel** [thephpleague/openapi-psr7-validator#87]
Hey guys,

Once more, not an issue, more like a request for feedback :)

For a couple of years now I've been using your package in Laravel projects to validate the responses returned by API endpoints against an OpenAPI definition, as part of integration tests.

Laravel uses Symfony's [HttpFoundation component](https://symfony.com/doc/current/components/http_foundation.html) under the hood for its HTTP messages, so what I'd do is I'd use Symfony's [PSR-7 Bridge](https://symfony.com/doc/current/components/psr7.html) to convert the HttpFoundation responses to PSR-7 messages first, and then use your package to validate the responses.

That resulted in the same classes that I'd copy over again and again in all of my projects, so I've decided to make a package out of it, to make my life easier and also because I think it could be useful to other people, seeing how much HttpFoundation is used in major projects and frameworks.

Here is the package: https://github.com/osteel/openapi-httpfoundation-validator

It's not published yet, as I would very much like your feedback on it first: is this the kind of project you expected people to build on top of yours? Does it make sense to you? Can you spot anything obviously wrong I'd be doing?

The package itself is rather simple, as it's made of a couple of classes only, and not huge ones. Hopefully a quick look at the README file will make it clear how it's supposed to be used.

If you've got a few spare minutes to have a look, that'd be awesome :)

No worries if not though!

Cheers,

Yannick

**Comment by osteel** [comment]
Oh and I've got a bonus question, too: may I ask why you've not released a 1.x version yet?

**Comment by canvural** [comment]
Yeah, this is a valid use case. I'm also doing this in my projects. The same idea can also be applied to requests. This package already provides PSR-15 compatible middleware to do it. But Laravel's middleware system does not use PSR-15. But it's really easy to do with this package. I created this some time ago: https://gist.github.com/canvural/0fb5f444b633f8a13fccc5d7e8d0c5d9

**Comment by osteel** [comment]
@canvural I've actually asked about examples of use cases for requests here [a few days ago](https://github.com/thephpleague/openapi-psr7-validator/issues/86), as I couldn't think of any. This was in preparation for this package, as I wasn't sure whether I should add support for them too, since I don't use them myself.

I've decided against in the end, as I see this package as a tool for the API maintainers, integrated with the API's test suite/codebase, to ensure consistency between the documentation and the actual responses.

Validating the requests would happen somewhere else, outside the API (for which the OpenAPI definition could be used, too).

**Comment by canvural** [comment]
@osteel If you are an API maintainer that means you might have some clients using your API. And validating requests with this package makes a lot of sense in that case. You wouldn't need to duplicate the logic to validate the request. You can treat the OpenAPI as the source of truth, and use it to validate.

**Comment by scaytrase** [comment]
Any API call is a two-side communication. The receiving side may want to ensure the incoming message conforms the API spec. For Request the receiving side is server, so server may want to validate the request before any further processing. For Reponse  the receiving side is client. And client also may want to validate the response before any further processing.

For testing purposes the transmitting side may want to validate their output as well before sending to be sure that everything is OK.

Also any intermediate system, like any implementation of message bus pattern may validate both request and response in order to ensure proper messaging between the systems

**Comment by osteel** [comment]
@canvural do you mean you'd validate incoming requests in order to decide whether to process them at all? Are we talking about a live situation here?

I see this package as a development tool, used in the context of automated tests. In which case I'm not sure how validating test requests would help? As like you said, there may be various clients using the API down the line, and I can't anticipate the requests they will send ("anticipate" as in "mocking them"). I don't know if that makes any sense?

Unless you're talking about end-to-end automated tests? If that's the case, I'd say that it'd be out of scope with regard to my package's intended purpose

**Comment by canvural** [comment]
@osteel Yes, I'm talking about live/production situations.

**Comment by scaytrase** [comment]
As for the package question. Despite of the fact I'd personally not sure I like this particular one (I'm not a fan of all-in-one god classes) I really like the idea. Having standards implemented in the main lib opens the doors for build this kinds of adapters for any custom validators for requests and responses which could be converted to the standard (PSR-7 in particular) ones.

So I'd really like to see people building this kind of packages around this lib and yes, not releasing 1.0 is problem here.
The reason for not doing this I think is that we (me in particular) are not sure, what the final API this lib should provide to you as end user, especially with not closed ideas like this https://github.com/thephpleague/openapi-psr7-validator/issues/83

I hope I can spend some time to review the lib and maybe do some overhaul in order to provide stable API to incorporate this lib as a part of other toolings

**Comment by osteel** [comment]
@scaytrase @canvural right, I think you guys are either considering a live situation indeed, where we'd want to validate incoming responses/requests from either side before processing them; or, a situation where the developers maintain both the client and the server, and want to perform end-to-end testing.

However, my main purpose with this package is to offer API developers a tool allowing them to ensure their API is in sync with the documentation they provide, and only that. They've got no control over who's gonna use the API, nor how, and it's not about live-checking incoming requests.

Does that make more sense?

**Comment by osteel** [comment]
@scaytrase that's right, my aim is to provide an adapter for HttpFoundation-based projects – to provide a specialised package based on your universal one.

> not releasing 1.0 is problem here

As my package is mostly intended for development, I think we're OK here.

> I'm not a fan of all-in-one god classes

Do you mind elaborating on this?

**Comment by scaytrase** [comment]
Yea,sure. I've mentioned this as 

> For testing purposes the transmitting side may want to validate their output as well before sending to be sure that everything is OK.

you can test the contents of your API call and you can test your API responses as well against the spec. So you can write a test that assert any of this

Actually all these things could be done in production as well, but since they affect performance they should be controller with some kinds of feature toggles.

**Comment by scaytrase** [comment]
> Do you mind elaborating on this?

The code you linked is a single class which is responsible for following
* Build (collecting) a configuration of validator
* Eager initializing validator 
* Perform a validation with this validator

This kind of classes is really hard to extend and tune for your needs since all things are coupled together.

**Comment by osteel** [comment]
@scaytrase 

> This kind of classes is really hard to extend and tune for your needs since all things are coupled together.

Ok, thank you. Yes, and I would say this is by design: your package is very flexible, and vendor/framework/purpose-agnostic, which makes it great to build upon, but also a bit complex.

What I'm trying to do here, is to abstract away that complexity for a specific use case; in other words, to make an opinionated and simplified use of your package.

By the way, the `Validator` class is `final`, so not meant to be extended.

**Comment by osteel** [comment]
@scaytrase I've just seen the edited bit of your answer

> since almost everything in this class is a point of extension (protected fields, non-finalized methods, etc.)

Sorry I'm not sure I follow here, since the `Validator` class (that's the one we're talking about, right?) is `final` and most of its methods are `private`, except for the intended public interface.

> Actually the only thing you allowed to change since you publish this package - is the private methods and fix bugs in public ones as people are making expectations of how your code now behaves

Well, yeah, which is again by design. Sorry, I fail to see how this is a problem?

I don't really have experience with publishing packages, so bear with me here :)

**Comment by scaytrase** [comment]
> By the way, the Validator class is final, so not meant to be extended.

Yea, sorry, that was in trait.

> I fail to see how this is a problem?

The class is final, it has a lot of responsibilities and no designited contracts (I mean the class itself is a  huge contract)

* You cannot extend it, i.e if I need to use my own Validator (i.e extended or decorated from https://github.com/thephpleague/openapi-psr7-validator/blob/master/src/PSR7/ResponseValidator.php)
* You cannot add more methods (like `options` or `head`) in any means
* You cannot create schema from string, not from file
* You even cannot create schema from file with no or custom extension
* It's hard to write any tests for code invoking this class

And the problem itself is that end user cannot solve this problems with any kind of tweaks for your package. So If user has string with schema instead of file - he is either forced to create a file or just copypaste your class without actually using your package. Or just skip the package and configure validator by hand.

You can solve these problems making your class two times bigger, but I'm sure these are not all the problems (these are just a brief look examples). 

The proper way is to give your end users certain extension points which can help them to solve tasks, which are not meant by the maintainer (you) initially, but which could be brought to your package later as a PR, since they can be solved using your package and not with skipping or duplicating the code. For example make mapping file to type protected and declare it an extension point

If I wrote package like this - it would look like the following

```php
// usage is almost the same

$validator = ResponseValidatorBuilder::fromFile($file)->build();
// using builders you can solve issues like this https://github.com/thephpleague/openapi-psr7-validator/issues/85 for example with `addFile` method
// or $validator = ResponseValidatorBuilder::fromString($file)->build();
// $validator is the wrapper class, not the real league validator, which does the internal conversion and so on
$validator->validate($method, $path, $response);
```

This code is as easy to use as yours. You can keep `ResponseValidatorBuilder` unsealed with proper extension points to allow users add method (like `addFile` or `fromString`)


This code is almost impossible to use in the wrong way.

if I call just
`(new Validator())->validate($response);` using your code - I'll get an exception. I have to read which method I have to call in order to set it up for real validation.

passing all the needed data in one signature - makes your IDE to tell all you need to call it
```
$validator->validate($method, $path, $response);
```

In my case building the validator and calling it - two different stages. I can build a validator using DI (i.e symfony) and pass the validator as a dependency. And can make my testing easier adding an interface to it.

I can keep on. The God Obejct - is common anti-pattern, so it's pretty easy to describe a lot of problems with it
https://en.wikipedia.org/wiki/God_object

**Comment by osteel** [comment]
@scaytrase points taken. I will go back to the drawing board for a bit and see how I can make things a bit better.

Thanks for the feedback! Much appreciated

**Comment by osteel** [comment]
@scaytrase I've updated the package: https://github.com/osteel/openapi-httpfoundation-testing

Summary of the changes:

* I renamed it from `openapi-httpfoundation-validator` to `openapi-httpfoundation-testing`;
* I made it clearer that it's intended to be used for development only, as part of a test suite;
* I've split the main class in 3: a builder like you suggested, the actual validator and also an adapter to convert HttpFoundation responses to PSR-7 messages;
* I've improved the package's extensibility overall, based on your remarks.

Thanks again for your time.

**Comment by scaytrase** [comment]
No problem, you're welcome. I'll closed for now, but feel free to continue discussion here if needed

**Comment by osteel** [comment]
@scaytrase yep no problem. I might keep you posted here, if you guys are interested

**Comment by osteel** [comment]
Hey guys, just to let you know I've now published the package and shared an article explaining [how it works](https://tech.osteel.me/posts/openapi-backed-api-testing-in-php-projects-a-laravel-example). Cheers!
